### ISSUE TITLE
Wrong temperatures

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#10]
Hi,

first: thank you for this great console client! :) Hope you keep it updated! :) Im missing a link to spend a coffee. ;)

Now the issue: Only the first thermostat has the correct temperatures in the list. The other are false.

![putty_2017-02-23_00-56-02](https://cloud.githubusercontent.com/assets/22779744/23239861/f1b1f98a-f969-11e6-9610-5034c4c7ca6c.png)

Best regards
Jens

**Comment by bpicode** [comment]
Hi,
thanks for the feedback. Much appreciated.
Can u say what values would have been correct one for the lower three devices? Did you configure a temperature offset for these?
Regards

**Comment by wassereimer86** [comment]
Hi,

they all have the same configuration as the first one. :) Saving is at 17°C and comfort is at 21°C.

Best regards
Jens

**Comment by bpicode** [comment]
Yeah, I think I found what the problem was. Will test it soon and provide a fix.

**Comment by wassereimer86** [comment]
Working perfectly now - thank you! :)

**Comment by bpicode** [comment]
OK, closing then. Thanks for reporting.
