### ISSUE TITLE
switch temperature to comfort/normal temperature

### ISSUE THREAD

**Issue by seppeel** [bpicode/fritzctl#136]
Hi, thanks for your efforts so far, fritzctl is great :-)

i would like to request a new feature:
 - switch to the predefined comfort temperature
 - switch to predefined economy temperature 
(i dont know if its called like this in the english translation of the fritzbox. in german its Komforttemperatur / Spartemperatur)

So you can use the predefined setting in the fritzbox.

Edit: Its "saving temperature"?

**Comment by bpicode** [comment]
Hi @seppeel.

Thanks for rising this issue. It sounds like a reasonable proposal. I will look into it soon™ (have very limited time on my hands rn).

Btw. yes it's "saving".

**Comment by bpicode** [comment]
Feature will be included in the next release. Thx again for reporting.
