### ISSUE TITLE
Separate Configuration Files

### ISSUE THREAD

**Issue by SnowBlinderP** [bpicode/fritzctl#137]
Hello

Is there a way to use different Configuration Files (2 Fritz Boxes)?

**Comment by bpicode** [comment]
Hi,

to answer your question: yes and no. Right now, there is no built-in "native" way to route between different boxes. However, assuming you use the latest release https://github.com/bpicode/fritzctl/releases/tag/v1.4.19, you can do it with the following trick:

* Put your two config files in two different folders.
* Delete any config files from the "general" locations (~/.fritzctl/config.yml, ~/.fritzctl/config.json, ~/.fritzctl, fritzctl.yml, ~/.fritzctl/fritzctl.json, ~/.fritzctl.yml, ~/.fritzctl.json).
* When running `fritzctl`, change your working directory to the respective folder and run your commands from there.

Hope that helps.

**Comment by SnowBlinderP** [comment]
Hi.

Thanks i will try that :)
