### ISSUE TITLE
Listing LanDevices not working with FRITZ OS 06.80

### ISSUE THREAD

**Issue by bpicode** [bpicode/fritzctl#14]
> cannot obtain LAN devices data: unable to parse remote response: json: cannot unmarshal string into Go struct field LanDevices.network of type []fritz.NetworkElement

**Comment by bpicode** [comment]
It seems that the newer versions of fritzOS is not service the lua interface anymore?

`GET https://fritz.box/query.lua?sid=<SESSSIONID>&network=landevice%3Asettings%2Flandevice%2Flist%28name%2Cip%2Cmac%2CUID%2Cdhcp%2Cwlan%2Cethernet%2Cactive%2Cstatic_dhcp%2Cmanu_name%2Cwakeup%2Cdeleteable%2Csource%2Conline%2Cspeed%2Cwlan_UIDs%2Cauto_wakeup%2Cguest%2Curl%2Cwlan_station_type%2Cethernet_port%2Cwlan_show_in_monitor%2Cplc%2Cparental_control_abuse%29`

responds with

`{"network":"landevice0"}`

**Comment by bpicode** [comment]
Apparently, these guys have the same problem:

https://github.com/jens-maus/hm_pdetect/issues/33

**Comment by wassereimer86** [comment]
Perhaps this Thread and the following pages can help?

https://homematic-forum.de/forum/viewtopic.php?t=27994&p=332577

**Comment by wassereimer86** [comment]
Same problem on 06.83

**Comment by bpicode** [comment]
Thanks for the pointer! I was able to get it working again!
cc @jens-maus : The following parameters must be omitted:

- static_dhcp
- manu_name
- wlan_UIDs
- auto_wakeup
- wlan_station_type
- ethernet_port
- wlan_show_in_monitor
- plc
- parental_control_abuse
