### ISSUE TITLE
fritzctl as a daemon?

### ISSUE THREAD

**Issue by seppeel** [bpicode/fritzctl#144]
I just wanna throw some ideas around :-)

i want to do some things which are currently not possible with the fritzbox.
 - use more than just two temperatures (comf/sav) in automated temperature switching plan
 - switch the temperature depending on other events (my example: switch to comf temperature as soon as my phone is connected via wlan)

this won't be a very big deal if i combine a bash script with cronjob and fritzctl (i already tried some things, although im a total scripting noob).
another possible solution could be an optional fritzctl daemon :-). a daemon could trigger things based on events and time.

if you think this should not be the job of fritzctl, just close this :-)

greetings
seppel

**Comment by bpicode** [comment]
Hi @seppeel,

these are some interesting ideas :tada:.

> use more than just two temperatures (comf/sav) in automated temperature switching plan

It certainly can be done using conventional scripting. I am planning to write a tutorial series on this using systemd-timers.

> switch the temperature depending on other events (my example: switch to comf temperature as soon as my phone is connected via wlan)

That's harder. A solution may be approximated by combining `list landevices` and `temperature ...` commands. There is however a conceptual problem. Fritz!BOXes do not support general notifications. I am still waiting for AVM to implement IFTTT support. So one basically has to resort to a polling approach like "ask every 60s: is the phone connected?". It is hard to pin down a reasonable interval, given that the user wants fast feedback after entering the house. On the other hand entering/leaving the house are events with frequency way larger than any conceivable polling frequency. So 99.9% of the polling will not result in any change. It is super inefficient and feels unnatural, but it can also be done using scripting.

> another possible solution could be an optional fritzctl daemon :-). a daemon could trigger things based on events and time.

A nice idea indeed. I have not yet made up my mind if that belongs here or be a separate project or be done at all. An useful event-trigger-action daemon boils down to writing a quite sophisticated rule engine while maintaining ease of configuration. And there are solutions out there. For example, I know a guy who was playing around with `fritzctl` and https://github.com/kalliope-project/kalliope (it's rather voice-centric but maybe it can be generalized).

I will leave the issue open for now. At the very least I will address typical scripting use-cases. Whether the daemonized `fritzctl` is going to happen is unclear atm.

Anyway, thanks for the input
Greetz

**Comment by bpicode** [comment]
FYI, I have written some stuff https://github.com/bpicode/fritzctl/wiki/Scheduling-temperature-changes

Closing this issue for now, I will keep the "daemon variant" in mind when planning the next features.

**Comment by seppeel** [comment]
Wow. Now that is a pretty nice tutorial!
