### ISSUE TITLE
Repo broken?

### ISSUE THREAD

**Issue by WizzardMaker** [bpicode/fritzctl#150]
I tried to install this via apt, but it says that it can't fetch from the given url:

> E: Failed to fetch https://dl.bintray.com/bpicode/fritzctl_deb/dists/stretch/InRelease
> E: Some index files failed to download. They have been ignored, or old ones used instead.

Its in the sources file:
> deb https://dl.bintray.com/bpicode/fritzctl_deb stretch main

but it fails to download it

**Comment by bpicode** [comment]
Hi @WizzardMaker,

thanks for reporting. I tried to reproduce and found the following warning 

> E: The method driver /usr/lib/apt/methods/https could not be found.
> N: Is the package apt-transport-https installed?
> E: Failed to fetch https://dl.bintray.com/bpicode/fritzctl_deb/dists/stretch/InRelease  
> E: Some index files failed to download. They have been ignored, or old ones used instead.

I did install
`apt install apt-transport-https`
and then it worked.

**Comment by bpicode** [comment]
Alternatively, you can edit `/etc/apt/sources.list` and replace 
`deb https://dl.bintray.com/bpicode/fritzctl_deb stretch main`
by
`deb http://dl.bintray.com/bpicode/fritzctl_deb stretch main`
(http instead of https).

**Comment by bpicode** [comment]
Closing this issue, feel free to reopen if further problems occur.
