### ISSUE TITLE
fritzctl ping fails: certificate signed by unknown authority - /etc/fritzctl/fritz.pem not correct

### ISSUE THREAD

**Issue by FranzGotsis** [bpicode/fritzctl#172]
I am having trouble getting the program to run. It seems that I am requiring a certificate that I do not have and that because of that the call to get fails 

fritzctl ping
2018/09/03 02:38:03 login failed:
  unable to solve login challenge:
  challenge not solved, got '0000000000000000' as session id, check login data

if I read the page http://fritz.box/login_sid.lua in the browser I get

<SessionInfo><SID>0000000000000000</SID><Challenge>1797e65e</Challenge><BlockTime>0</BlockTime><Rights/></SessionInfo>

Any help is appreciated.

**Comment by bpicode** [comment]
Hi @FranzGotsis,

thanks for reporting this issue.
Let me give my thoughts:

> It seems that I am requiring a certificate that I do not have and that because of that the call to get fails

One can turn certificate validation off by setting `skip_tls_verify: true` in the config file. You can run `fritzctl configure` for interactive configuration. If you don't want to set `skip_tls_verify`, there is an option to export it: `fritzctl certificate export`.

> unable to solve login challenge:

usually this means that the username/password combination is wrong. Did you check that it is correct?

Greets

**Comment by bpicode** [comment]
Closed for inactivity. Feel free to reopen, if necessary.
