### ISSUE TITLE
Mac OS installation via Homebrew

### ISSUE THREAD

**Issue by qnaalx** [bpicode/fritzctl#173]
Hello,

I try to install fritzctl on Mojave and get the following error

brew install bpicode/tap/fritzctl
==> Installing fritzctl from bpicode/tap
==> Downloading https://github.com/bpicode/fritzctl/releases/download/v1.4.23/fr
Already downloaded: /Users/danny/Library/Caches/Homebrew/downloads/8feb3e4881ff3b8b123a5c80bccaab9f7c7438d47cb38d7be4af44b3c1d985fa--fritzctl-1.4.23-darwin-amd64.zip
Error: No such file or directory - build/distibutions/darwin_amd64/fritzctl

**Comment by bpicode** [comment]
Hi, thanks bringing this issue up! There was a typo in the brew formula. Can you try again?

**Comment by qnaalx** [comment]
Hi, 
still borken
`danny@dMac:~ $ brew install bpicode/tap/fritzctl
==> Installing fritzctl from bpicode/tap
==> Downloading https://github.com/bpicode/fritzctl/releases/download/v1.4.23/fritzctl-1.4.23-darwin-amd64.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/71268827/6836d066-8cf4-11e8-8106-59a
######################################################################## 100.0%
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  Errno::ENOENT: No such file or directory - build/distributions/darwin_amd64/fritzctl`

**Comment by bpicode** [comment]
I will test this at a later point, don't have a mac at my hand right now. In the meantime you can pull the binary directly from https://github.com/bpicode/fritzctl/releases/download/v1.4.23/fritzctl-darwin-amd64.

**Comment by bpicode** [comment]
@qnaalx I took another attempt at fixing the brew installation. Could reproduce and fix the error with github.com/Linuxbrew/brew. If you are still interested, you can try again.

**Comment by bpicode** [comment]
Closing this. Feel free to re-open if further problems occur.
