### ISSUE TITLE
WOL enhancement

### ISSUE THREAD

**Issue by seppeel** [bpicode/fritzctl#177]
hi,
i want to wake my machines at home with my fritzbox via fritzctl.
is it possible to add
fritzctl wol <landevice_name>
for devices listed as landevice (fritzctl list landevices)

You can find the button for this in the fritzos ui when you click on a device in the network devices list.

that would be nice :)

thanks
seppel

**Comment by shkm** [comment]
@seppeel you can just use `wakeonlan` for this and pass it a MAC address.

**Comment by seppeel** [comment]
Yes, thats a lot easier.
But its another programm and you need to have a linux machine running for it.
Maybe one wants to start devices at home without having a machine running for this.
