### ISSUE TITLE
Make a package for Synology NAS devices

### ISSUE THREAD

**Issue by seppeel** [bpicode/fritzctl#179]
Hi :)

it would be great to make fritzctl available to some "always on" devices such as NAS Systems.
In my Setup i use an additional raspi for my fritzctl stuff. This additional hardware wouldnt be neccessary if fritzctl would be available for my Synology NAS.
Third party package sources are possible on synology devices.

If you think this is a good idea at all, i would try to help you out with things like how the packages have to be placed on a webserver and testing stuff.

greetings
seppel

**Comment by bpicode** [comment]
Hi @seppeel,

in my opinion this is a reasonable proposal and I hope it can be done.

To manage expectations, I would like to comment on some stuff.
* I'm no expert on Synology NAS, I don't have one ;)
* Just cross-compiling to the target system and copy the binary to the NAS would be be a low hanging fruit, but that is probably not enough. Providing an `spk` somehow is the way to go.
* How good is the toolchain support? People are mostly using [spksrc](https://github.com/SynoCommunity/spksrc). Apparently they got [syncthing](https://github.com/syncthing/syncthing) to work, which makes me confident that it could work here, too.
* Which CPU architectures? There seem to be a lot, depending on the [model](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have). Not all of them are known to work with go, see https://github.com/SynoCommunity/spksrc/issues/3456 and https://github.com/golang/go/issues/22885. So if your model is PPC32, this is bad news.
* Testing the spk on real devices would be great, I can also ask some friends for help.
* Package hosting: Preferably, I would go for an existing community repo. I don't see hosting the stuff myself. My usual go-to hosting, bintray, doesn't support spk.

Apart from that, I can spare very little time working on this project atm :(. I am hoping to do coherent work on fritzctl before Christmas holidays.

Greets

**Comment by seppeel** [comment]
Hi!

To be honest i didnt even know about the synocommunity repo, all my custom packages had own repos. But i agree, using the existing community repo would be the best way.

I found a nice list of CPUs used in the official Synology documentation:
https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

The SynoCommunity made a nice (and very long, ouch) list of architectures currently used:
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
For me it looks like PPC archtitectures are no longer supported anyways, so good news for this.

To provide an example for a repo i used (with some architectures):
http://syno.dierkse.nl/

I personally use a small DS115j with **Marvell Armada 370 88F6707** cpu (armada370).
 -> I can test a spk on this device for you.

No hurry, i just bought a house and won't be able to big things on my home network before january ;-)

Let me know whenever i can provide some support for you.

Greetings

**Comment by seppeel** [comment]
yeah, i will keep an eye on it and give you feedback as soon as its available :)

**Comment by bpicode** [comment]
I have some preview packages; rename .gz to .spk (github doesn't let me upload spk).
[fritzctl_x64-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723748/fritzctl_x64-6.1_1.4.23-1.gz)
[fritzctl_rtd1296-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723749/fritzctl_rtd1296-6.1_1.4.23-1.gz)
[fritzctl_northstarplus-1.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723750/fritzctl_northstarplus-1.1_1.4.23-1.gz)
[fritzctl_monaco-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723751/fritzctl_monaco-6.1_1.4.23-1.gz)
[fritzctl_kvmx64-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723752/fritzctl_kvmx64-6.1_1.4.23-1.gz)
[fritzctl_ipq806x-1.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723753/fritzctl_ipq806x-1.1_1.4.23-1.gz)
[fritzctl_hi3535-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723754/fritzctl_hi3535-6.1_1.4.23-1.gz)
[fritzctl_evansport-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723755/fritzctl_evansport-6.1_1.4.23-1.gz)
[fritzctl_dockerx64-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723756/fritzctl_dockerx64-6.1_1.4.23-1.gz)
[fritzctl_denverton-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723757/fritzctl_denverton-6.1_1.4.23-1.gz)
[fritzctl_comcerto2k-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723758/fritzctl_comcerto2k-6.1_1.4.23-1.gz)
[fritzctl_armadaxp-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723759/fritzctl_armadaxp-6.1_1.4.23-1.gz)
[fritzctl_armada375-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723760/fritzctl_armada375-6.1_1.4.23-1.gz)
[fritzctl_armada370-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723761/fritzctl_armada370-6.1_1.4.23-1.gz)
[fritzctl_armada38x-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723762/fritzctl_armada38x-6.1_1.4.23-1.gz)
[fritzctl_armada37xx-6.2_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723763/fritzctl_armada37xx-6.2_1.4.23-1.gz)
[fritzctl_alpine-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723764/fritzctl_alpine-6.1_1.4.23-1.gz)
[fritzctl_aarch64-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723765/fritzctl_aarch64-6.1_1.4.23-1.gz)
[fritzctl_88f6281-6.1_1.4.23-1.gz](https://github.com/bpicode/fritzctl/files/2723766/fritzctl_88f6281-6.1_1.4.23-1.gz)

**Comment by bpicode** [comment]
No worries. Best of luck with your new house :)

**Comment by bpicode** [comment]
Good to know. Thanks for testing.

> Now we just have to wait for synocli-net to be shipped with fritzctl :)

Well, I don't know how often they do releases. I can understand that they don't do it every day... compiling for all those platforms takes forever and takes a lot of disk space.
