### ISSUE TITLE
runtime error: index out of range (inetstats with FRITZ!OS: 07.01)

### ISSUE THREAD

**Issue by TeddyKopernikus** [bpicode/fritzctl#182]
fritzctl 1.4.23 with FritzBox 7490 with FRITZ!OS: 07.01 gets me the output:

> fritzctl list inetstats
2018/11/01 09:09:54 Login successful
2018/11/01 09:09:54 runtime error: index out of range

With morelog-output it looks like this:
[I hope the removed challenges, SID and IP are not relevant.]

> fritzctl --loglevel debug list inetstats

2018/11/01 09:10:26 DATA: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>XXXXXXXX</Challenge><BlockTime>0</BlockTime><Rights></Rights></SessionInfo>
2018/11/01 09:10:26 FRITZ!Box challenge is XXXXXXXX
2018/11/01 09:10:26 DATA: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>XXXXXXXXXXXXXXXX</SID><Challenge>XXXXXXXX</Challenge><BlockTime>0</BlockTime><Rights><Name>Dial</Name><Access>2</Access><Name>App</Name><Access>2</Access><Name>HomeAuto</Name><Access>2</Access><Name>BoxAdmin</Name><Access>2</Access><Name>Phone</Name><Access>2</Access></Rights></SessionInfo>
2018/11/01 09:10:26 Login successful
2018/11/01 09:10:26 GET https://192.168.XXX.XXX/internet/inetstat_monitor.lua?sid=XXXXXXXXXXXXXXXX&useajax=1&action=get_graphic
2018/11/01 09:10:27 DATA: <script>if (typeof jxl === 'undefined') {
location.href = "/";
}
</script>
<link rel="stylesheet" type="text/css" href="/css/default/chartist.css">
<link rel="stylesheet" type="text/css" href="/css/default/chartistplugins.css">
<link rel="stylesheet" type="text/css" href="/css/default/inetstat.css">
<style type="text/css">
main table.newzebra {
border-collapse: collapse;
width: 100%;
margin: 1rem 0;
}
main table.newzebra td,
main table.newzebra th {
padding: 0.125rem 0.5rem;
}
main table.newzebra td {
vert
2018/11/01 09:10:27 runtime error: index out of range

Any ideas about this behaviour?

It worked fine with the FRITZ!OS 06.XX before, so I'm pretty sure it's related to the update.

Further information on the FritzBox:

> fritzctl boxinfo
2018/11/01 09:18:49 Login successful
Model:     FRITZ!Box 7490 (UI), ADSL standard 'B', branded as '1und1'
Firmware:  FRITZ!OS 07.01 (113.07.01 revision 61077)
Running:   2 years, X months, XX days, XX hours, XXX reboots

The other commands seem to work fine so far.

**Comment by bpicode** [comment]
Hi, thanks for bringing this up! It is known issue with FRITZ!OS 07.xx. It has been addressed in current git/master [1]. The fix will be shipped with the next release, therefore I will close the issue for now.

[1] https://github.com/bpicode/fritzctl/commit/f117d8ac37f01563cc2ec4697a62e77ae4ce2244
