### ISSUE TITLE
temperature save and comfort are exchanged

### ISSUE THREAD

**Issue by joerggollnick** [bpicode/fritzctl#203]
In temperature.go setting comfort temperature sets saving temperature and vice versa.
(tested with two devices and result was 34 for 17°C (saving) when setting comfort temperature)
Suggested fix:
rename functions in line 57 and 63.

**Comment by bpicode** [comment]
Oops. Thanks for noticing :)

**Comment by bpicode** [comment]
Fixed on master, will be shipped with next release.
