### ISSUE TITLE
letter are displayed incorrect

### ISSUE THREAD

**Issue by Maik-100** [bpicode/fritzctl#208]
If I typ it:
" fritzctl list switches"
I got:
2019/03/31 22:41:14 Login successful
2019/03/31 22:41:14 Device data:

+------------+--------------------+---------+-------+----------------+---------+--------+-----------+---------+---------+
|    NAME    |      PRODUCT       | PRESENT | STATE | LOCK (BOX/DEV) |  MODE   | POWER  |  ENERGY   |  TEMP   | OFFSET  |
+------------+--------------------+---------+-------+----------------+---------+--------+-----------+---------+---------+
| WohnZimmer | AVM FRITZ!DECT 200 | â       | â     | â/â            | auto    | 0.92 W |   53 Wh | 23.5 Â°C |   -1 Â°C |
| WaescheTr  | AVM FRITZ!DECT 200 | â       | â     | â/â            | manuell | 0.28 W | 61 Wh |   19 Â°C | -3.5 Â°C |
| Balkon_aus | AVM FRITZ!DECT 210 | â       | â     | â/â            | auto    |    0 W |    86 Wh |  9.5 Â°C |    0 Â°C |
+------------+--------------------+---------+-------+----------------+---------+--------+-----------+---------+---------+
pi@raspberrypi:~ $
pi@raspberrypi:~ $ fritzctl list thermostats
2019/03/31 22:41:30 Login successful
2019/03/31 22:41:30 Device data:

+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+-----                                                         ----+
|          NAME          |    PRODUCT     | PRESENT | LOCK (BOX/DEV) | MEASURED | OFFSET | WANT  | SAVING | COMFORT |            NEXT             | STATE | BATT                                                         ERY |
+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+-----                                                         ----+
| WohnZimmer_Heizung Hof | AVM Comet DECT | â       | â/â            |    23 Â°C |  -1 Â°C | 19 Â°C |  19 Â°C |   22 Â°C | Tue Apr 2 05:30:00 -> 22 Â°C | â                                                              | â       |
+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+-----                                                         ----+
pi@raspberrypi:~ $
pi@raspberrypi:~ $ fritzctl list thermostats
2019/03/31 22:41:40 Login successful
2019/03/31 22:41:40 Device data:

+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+---------+
|          NAME          |    PRODUCT     | PRESENT | LOCK (BOX/DEV) | MEASURED | OFFSET | WANT  | SAVING | COMFORT |            NEXT             | STATE | BATTERY |
+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+---------+
| WohnZimmer_Heizung Hof | AVM Comet DECT | â       | â/â            |    23 Â°C |  -1 Â°C | 19 Â°C |  19 Â°C |   22 Â°C | Tue Apr 2 05:30:00 -> 22 Â°C | â     | â       |
+------------------------+----------------+---------+----------------+----------+--------+-------+--------+---------+-----------------------------+-------+---------+
pi@raspberrypi:~ $

I see "â       | â/â". In your small demo I saw a cross and a hook.
I presuming a problem with my terminal settings. So I check it:
pi@raspberrypi:~ $ locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8
pi@raspberrypi:~ $ cat /etc/default/locale
#  File generated by update-locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
LC_ALL=de_DE.UTF-8
pi@raspberrypi:~ $

It seems to be ok.
Were is the Problem?

**Comment by bpicode** [comment]
Hi @Maik-100 

are you interacting with your raspberry directly or are you connecting to it using a client like putty. My best guess is to check the settings in the client, see e.g. https://serverfault.com/questions/475925/how-to-fix-putty-showing-garbled-characters

Cheers
