### ISSUE TITLE
unable to obtain login challenge

### ISSUE THREAD

**Issue by Woastscho** [bpicode/fritzctl#214]
I have a 7390 with Fritz!OS 6.86.
I get 
 " unable to obtain login challenge:
  error obtaining HTTP response from remote:
  Get https://fritz.box/login_sid.lua: dial tcp 192.168.1.1:443: connect: connection refuse"
with "fritzctl boxinfo".

I tried with user/pw , without pw, skip TLS true/false.
Always the same error
Any idea ?

**Comment by bpicode** [comment]
Hi, can you try to set protocol=http in the configuration? It might be that the fritzbox does not listen on port 443 (should be configurable somewhere in the UI).

**Comment by Woastscho** [comment]
That solved the problem !
Thx
