### ISSUE TITLE
Signing key invalid

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#215]
Tried to re-add the key with

`wget -qO - https://api.bintray.com/users/bpicode/keys/gpg/public.key | sudo apt-key add -`

but it doesn´t worked.

` Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: https://dl.bintray.com/bpicode/fritzctl_deb buster Release: Die folgenden Signaturen waren ungültig: EXPKEYSIG 15XXXXXXXXXX39 bpicode fitzctl debian repository (Key for fritzctl debian repository) <bpXXXX.XXXXXXX.XXXXXXX@XXXXXX.io>
`

**Comment by t-offline** [comment]
Hi,
the key expired on Thu Nov  7 20:19:51 CET 2019.
Please generate a new one.

> root@mimosa:~# date
Di 19. Nov 10:31:19 CET 2019

> root@mimosa:~# wget -qO - https://api.bintray.com/users/bpicode/keys/gpg/public.key | pgpdump
Old: Public Key Packet(tag 6)(1198 bytes)
	Ver 4 - new
	Public key creation time - Mon Nov  7 20:19:51 CET 2016
	Pub alg - DSA Digital Signature Algorithm(pub 17)
	DSA p(3072 bits) - ...
	DSA q(256 bits) - ...
	DSA g(3070 bits) - ...
	DSA y(3071 bits) - ...
Old: User ID Packet(tag 13)(110 bytes)
	User ID - bpicode fitzctl debian repository (Key for fritzctl debian repository) <bpicode.debian.repository@fritzctl.io>
Old: Signature Packet(tag 2)(127 bytes)
	Ver 4 - new
	Sig type - Positive certification of a User ID and Public Key packet(0x13).
	Pub alg - DSA Digital Signature Algorithm(pub 17)
	Hash alg - SHA256(hash 8)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Mon Nov  7 20:19:51 CET 2016
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to certify other keys
		Flag - This key may be used to sign data
	Hashed Sub: key expiration time(sub 9)(4 bytes)
		Time - Thu Nov  7 20:19:51 CET 2019
	Hashed Sub: preferred symmetric algorithms(sub 11)(4 bytes)
		Sym alg - AES with 256-bit key(sym 9)
		Sym alg - AES with 192-bit key(sym 8)
		Sym alg - AES with 128-bit key(sym 7)
		Sym alg - Triple-DES(sym 2)
	Hashed Sub: preferred hash algorithms(sub 21)(5 bytes)
		Hash alg - SHA256(hash 8)
		Hash alg - SHA384(hash 9)
		Hash alg - SHA512(hash 10)
		Hash alg - SHA224(hash 11)
		Hash alg - SHA1(hash 2)
	Hashed Sub: preferred compression algorithms(sub 22)(3 bytes)
		Comp alg - ZLIB <RFC1950>(comp 2)
		Comp alg - BZip2(comp 3)
		Comp alg - ZIP <RFC1951>(comp 1)
	Hashed Sub: features(sub 30)(1 bytes)
		Flag - Modification detection (packets 18 and 19)
	Hashed Sub: key server preferences(sub 23)(1 bytes)
		Flag - No-modify
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x15FCCFC935E71039
	Hash left 2 bytes - 6b 61 
	DSA r(254 bits) - ...
	DSA s(254 bits) - ...
		-> hash(DSA q bits)

**Comment by bpicode** [comment]
Hi, I have extended the validity of the key.

Affected users will have to run
`wget -qO - https://api.bintray.com/users/bpicode/keys/gpg/public.key | sudo apt-key add -`
to update.

Thanks for your patience.
