### ISSUE TITLE
Use template

### ISSUE THREAD

**Issue by seppeel** [bpicode/fritzctl#220]
Its possible to define templates in the fritzbox for smart home devices. A fritzctl command to use a predefined template could summarize actions like changing temperatures on many thermostats.

Thanks for your work.

**Comment by bpicode** [comment]
It is not possible yet, but on the roadmap, https://github.com/bpicode/fritzctl/issues/188.
Closing in favor of https://github.com/bpicode/fritzctl/issues/188
