### ISSUE TITLE
Adding battery state to json output

### ISSUE THREAD

**Issue by Wiki591** [bpicode/fritzctl#231]
Hi,

this tool for me is the ultimate integration of my Dect thermostats into my smart home network, thanks a lot for sharing it.

I am reading the current and the goal temperatures using an OrangePi to scan the json output and displaying them on a tiny 4.2" Nextion touch screen using ESPEasy. Changing the goal temperatures manually using the touch screen is the next step. In parallel the temperatures are sent to my Domoticz controller.

It would be nice, if the json output would contain the battery state of the devices. For me would be the cherry on the top.

Btw.: I was looking for a donate button?

Sorry, I forgot: I am using the .deb package fritzctl_1.4.23_armhf.deb because on an OrangePi compiling from sources doesn't work.

**Comment by bpicode** [comment]
Hi, thanks for the nice words. Much appreciated.

> It would be nice, if the json output would contain the battery state of the devices. For me would be the cherry on the top.

It is possible. Apparently, newer versions of FritzOS also tell about the battery capacity (in percent). A lot of new features could be unlocked in general, but I struggle to find time integrating these.

> Btw.: I was looking for a donate button?

You can stop looking, there is none ;) And there will never be one. The biggest problem is my lack of time.

> Sorry, I forgot: I am using the .deb package fritzctl_1.4.23_armhf.deb because on an OrangePi compiling from sources doesn't work.

Never tested compiling on these platforms. What I typically do (and that is also the way this project is released), is cross-compile from my standard machine.

Anyway, I hope that can get some coherent work done during my Christmas vacation.

Cheers

**Comment by Wiki591** [comment]
Thanks for fast reaction. I appreciate.

**Comment by bpicode** [comment]
Implemented within d7796181161c6346fbf8c5126ca3d79bc67b5d47. Will be part of the next release.

**Comment by Wiki591** [comment]
...and window open/close state added, too.

Thanks a lot!
