### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#55]
It would be great if the README.md would also contain an "How to update this tool" area depending on how it was installed.

**Comment by bpicode** [comment]
Hi,
let me ask: did you have any trouble updating? How did you install?

**Comment by wassereimer86** [comment]
I´ve installed it under Debian like in the documentation. I´m running Debian Stretch but added the Jessie repository. It´s working. But i´m not sure if apt-get update & apt-get upgrade really would update it.
