### ISSUE TITLE
fritzctl temperature on/off

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#58]
Is there a way to turn on/off the thermostats like direct in the Fritz!Box or at the device? In the help it says only: fritzctl temperature [value in °C] [device names] [flags]

**Comment by bpicode** [comment]
Right now it seems that it is not possible. It may become available with newer FB software. The FB UI still offers more features than the official interface. I will leave this issue open for the time being. It happened a few times in the past that AVM extended their interface.

**Comment by bpicode** [comment]
@wassereimer86 Can you check if

```bash
fritzctl temperature 127 device
fritzctl temperature 126.5 device
```

is doing anything useful for you? This seems to be working.

**Comment by wassereimer86** [comment]
Yes,  it´s working! The first one is "on" and the other is "off". It would be great if you can add it with an alias. E.g. that you can type "fritzctl temperature on/off device" and that it´s making the correct request in the background.

Off-topic: I would love to help but i don´t know the GO-Language. My hobby is PHP/HTML and a bit of Java/Javascript. And by the way: I am writing a long blog post atm to get Google Home the ability to control AVM devices with your tool. :) That´s also the reason why i opened so much issues - i found them while working extensive with your great tool. :D

**Comment by bpicode** [comment]
That's awesome, I would love to read the blog post. Thank you for the feedback. 
Btw. reporting issues does help a lot. Code is important, but is only one ingredient to a project ;)

**Comment by wassereimer86** [comment]
It´s in german. But here it is: https://www.randnotizen.org/fritzbox-aha-avm-home-automation-mit-google-home-steuern/

**Comment by bpicode** [comment]
Very nice! I admire that you have seen it through to the very end. Can imagine that there was quite some cursing involved in intermediate steps ;) Dropped a comment over at the blog.

**Comment by wassereimer86** [comment]
Yes, it took me a few days from the idea to a working solution. And because i wasn´t able to find any helpfull tutorials or howto´s on the internet i decided to write a blog post about it. - I already replied. :)
