### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#60]
It would be great to control groups specified in the FRITZ!Box. But only clean groups should be listet (only switches/only thermostats). And "fritzctl list groups" should also be added if the whole thing is possible and you want to do it.

**Comment by bpicode** [comment]
I guess this should be possible.

**Comment by bpicode** [comment]
Btw.: Right now it is possible to snapshot current states `fritzctl manifest export  --help`, which you can edit and apply `fritzctl manifest plan  --help`, `fritzctl manifest apply  --help`. This would virtually provide bulk-operations. It is not the same as the control groups, but it is useful for larger setups.

**Comment by wassereimer86** [comment]
Thank you for the information but for me it´s too complicated to use it this way. :)
