### ISSUE TITLE
.deb Package

### ISSUE THREAD

**Issue by wassereimer86** [bpicode/fritzctl#65]
The .deb package is only indexed for jessie and wheezy. Shoulkd it be like this? I use it without problems on stretch.

**Comment by bpicode** [comment]
It is true that only jessie and wheezy are in the repo. I will add stretch for future releases. Since this project uses go (zero-dependencies, single binary) it will work fine with tilted repo/distro combinations as in your case.

**Comment by bpicode** [comment]
Closing this thread in favor of #55.
